# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a69ba61bc65d8c40797f665acedc09c1a5ed3ca9208ff2336f4e6aa64b1f43abea29222be5568dc92c55d4c7771e9cfb08d623a828f78099383b909abedf6e8

test:
  secret_key_base: 2192d2dbb3a531b1d950c1a31dc6b377000c79ba363bf891230539f0ad21c0b70f79a5b5c951307372b9359de79ec12ee3ad779905b88c6b37dcf8e085a81ec9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
